version: '3'

services:
  app:
    build:
      context: .
    container_name: taskslist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/taskslist?currentSchema=taskslist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8090:8090'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DB=taskslist
    volumes:
      - ./src/main/resources/db-init/:/docker-entrypoint-initdb.d



